/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Metadata = {
	_type: 'metadata'
	title?: string
	description?: string
	slug?: Slug
}

export type Domain = {
	_id: string
	_type: 'domain'
	_createdAt: string
	_updatedAt: string
	_rev: string
	name?: string
	subdomains?: Array<string>
}

export type Project = {
	_id: string
	_type: 'project'
	_createdAt: string
	_updatedAt: string
	_rev: string
	url?: string
	title?: string
	isClient?: boolean
	redacted?: boolean
}

export type Global = {
	_id: string
	_type: 'global'
	_createdAt: string
	_updatedAt: string
	_rev: string
	tagline?: string
	featuredProjects?: Array<{
		_ref: string
		_type: 'reference'
		_weak?: boolean
		_key: string
		[internalGroqTypeReferenceTo]?: 'project'
	}>
	cars?: Array<{
		asset?: {
			_ref: string
			_type: 'reference'
			_weak?: boolean
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
		}
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
		_key: string
	}>
}

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch'
	background?: string
	foreground?: string
	population?: number
	title?: string
}

export type SanityImagePalette = {
	_type: 'sanity.imagePalette'
	darkMuted?: SanityImagePaletteSwatch
	lightVibrant?: SanityImagePaletteSwatch
	darkVibrant?: SanityImagePaletteSwatch
	vibrant?: SanityImagePaletteSwatch
	dominant?: SanityImagePaletteSwatch
	lightMuted?: SanityImagePaletteSwatch
	muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions'
	height?: number
	width?: number
	aspectRatio?: number
}

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot'
	x?: number
	y?: number
	height?: number
	width?: number
}

export type SanityImageCrop = {
	_type: 'sanity.imageCrop'
	top?: number
	bottom?: number
	left?: number
	right?: number
}

export type SanityFileAsset = {
	_id: string
	_type: 'sanity.fileAsset'
	_createdAt: string
	_updatedAt: string
	_rev: string
	originalFilename?: string
	label?: string
	title?: string
	description?: string
	altText?: string
	sha1hash?: string
	extension?: string
	mimeType?: string
	size?: number
	assetId?: string
	uploadId?: string
	path?: string
	url?: string
	source?: SanityAssetSourceData
}

export type SanityImageAsset = {
	_id: string
	_type: 'sanity.imageAsset'
	_createdAt: string
	_updatedAt: string
	_rev: string
	originalFilename?: string
	label?: string
	title?: string
	description?: string
	altText?: string
	sha1hash?: string
	extension?: string
	mimeType?: string
	size?: number
	assetId?: string
	uploadId?: string
	path?: string
	url?: string
	metadata?: SanityImageMetadata
	source?: SanityAssetSourceData
}

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata'
	location?: Geopoint
	dimensions?: SanityImageDimensions
	palette?: SanityImagePalette
	lqip?: string
	blurHash?: string
	hasAlpha?: boolean
	isOpaque?: boolean
}

export type Geopoint = {
	_type: 'geopoint'
	lat?: number
	lng?: number
	alt?: number
}

export type Slug = {
	_type: 'slug'
	current?: string
	source?: string
}

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData'
	name?: string
	id?: string
	url?: string
}

export type AllSanitySchemaTypes =
	| Metadata
	| Domain
	| Project
	| Global
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageHotspot
	| SanityImageCrop
	| SanityFileAsset
	| SanityImageAsset
	| SanityImageMetadata
	| Geopoint
	| Slug
	| SanityAssetSourceData
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ./src/routes/(frontend)/+layout.server.ts
// Variable: LAYOUT_QUERY
// Query: {		'global': *[_type == 'global'][0]{			...,			featuredProjects[]->		},		'projects': *[_type == 'project' && defined(url)],		'domains': *[_type == 'domain'],	}
export type LAYOUT_QUERYResult = {
	global: {
		_id: string
		_type: 'global'
		_createdAt: string
		_updatedAt: string
		_rev: string
		tagline?: string
		featuredProjects: Array<{
			_id: string
			_type: 'project'
			_createdAt: string
			_updatedAt: string
			_rev: string
			url?: string
			title?: string
			isClient?: boolean
			redacted?: boolean
		}> | null
		cars?: Array<{
			asset?: {
				_ref: string
				_type: 'reference'
				_weak?: boolean
				[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
			}
			media?: unknown
			hotspot?: SanityImageHotspot
			crop?: SanityImageCrop
			alt?: string
			_type: 'image'
			_key: string
		}>
	} | null
	projects: Array<{
		_id: string
		_type: 'project'
		_createdAt: string
		_updatedAt: string
		_rev: string
		url?: string
		title?: string
		isClient?: boolean
		redacted?: boolean
	}>
	domains: Array<{
		_id: string
		_type: 'domain'
		_createdAt: string
		_updatedAt: string
		_rev: string
		name?: string
		subdomains?: Array<string>
	}>
}

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
	interface SanityQueries {
		"{\n\t\t'global': *[_type == 'global'][0]{\n\t\t\t...,\n\t\t\tfeaturedProjects[]->\n\t\t},\n\t\t'projects': *[_type == 'project' && defined(url)],\n\t\t'domains': *[_type == 'domain'],\n\t}": LAYOUT_QUERYResult
	}
}
